# Generated by Django 4.2.27 on 2025-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gutenberg_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
